

display the title of the game "Crystals Collector!"

show a set of instructions on how to pay the game.

show a random number generated by the random number function. a new random number 
when the player (wins or losses)

show the number of wins and losses

Show a row of clickable crystals that have a random number assigned to them
each time the game is played. Each crystal gets a new random number when the
player (wins or losses)

During the game, as Crystals are clicked, add up their collective value
and show it on screen in a box as the value is being increased.THis is a box
that shows Total_Score. The total score is set back to zero each time the
player (wins or losses).



